import * as React from 'react';
import {RouteComponentProps} from 'react-router';
import {DataLoader, Page} from '../../shared/components';
import * as models from '../../shared/models';
import {services} from '../../shared/services';
import {ProjectAppList, ProjectAppListView, ViewToggle} from './project-app-list';
import {getOwningAppSetName} from './projects-utils';

// AppSetDetail lists the Applications generated by a single ApplicationSet.
// Selecting an Application opens its details page.
export const AppSetDetail = (props: RouteComponentProps<{name: string; appset: string}>) => {
    const projectName = props.match.params.name;
    const appSetName = props.match.params.appset;
    const [view, setView] = React.useState<ProjectAppListView>('tiles');

    return (
        <Page
            title={appSetName}
            toolbar={{
                breadcrumbs: [{title: 'Projects', path: '/projects'}, {title: projectName, path: `/projects/${projectName}`}, {title: appSetName}],
                tools: <ViewToggle view={view} onChange={setView} />
            }}>
            <div className='argo-container'>
                <DataLoader key={appSetName} load={() => services.applications.list([], 'application')}>
                    {appList => {
                        const apps = (appList.items || []) as models.Application[];
                        const ownedApps = apps.filter(app => getOwningAppSetName(app) === appSetName);
                        return <ProjectAppList applications={ownedApps} view={view} emptyTitle='This ApplicationSet has no Applications' />;
                    }}
                </DataLoader>
            </div>
        </Page>
    );
};
