import * as models from '../../shared/models';

// getOwningAppSetName returns the name of the ApplicationSet that owns the given
// Application (via an ownerReference), or null when the Application is standalone.
export function getOwningAppSetName(app: models.Application): string | null {
    const ref = (app.metadata.ownerReferences || []).find(r => r.kind === 'ApplicationSet');
    return ref ? ref.name : null;
}

// appsInProject returns the Applications whose spec.project matches projectName.
export function appsInProject(apps: models.Application[], projectName: string): models.Application[] {
    return apps.filter(app => app.spec.project === projectName);
}

// standaloneApps returns the Applications that are not generated by an ApplicationSet.
export function standaloneApps(apps: models.Application[]): models.Application[] {
    return apps.filter(app => getOwningAppSetName(app) === null);
}

// appSetsInProject returns the ApplicationSets that own at least one Application
// belonging to the given project. ApplicationSets have no project of their own,
// so their project membership is derived from the Applications they generate.
export function appSetsInProject(apps: models.Application[], appSets: models.ApplicationSet[], projectName: string): models.ApplicationSet[] {
    const ownerNames = new Set(
        appsInProject(apps, projectName)
            .map(getOwningAppSetName)
            .filter((name): name is string => !!name)
    );
    return appSets.filter(appSet => ownerNames.has(appSet.metadata.name));
}
