import * as models from '../../shared/models';

// getAppSetGeneratedAppNames returns the Application names that an ApplicationSet
// claims to manage, derived from its status. This is more reliable than walking
// ownerReferences on each Application because the list API's field allowlist
// may strip ownerReferences from responses.
export function getAppSetGeneratedAppNames(appSet: models.ApplicationSet): Set<string> {
    const names = new Set<string>();
    (appSet.status?.resources || []).forEach(r => {
        if (r?.name) {
            names.add(r.name);
        }
    });
    (appSet.status?.applicationStatus || []).forEach(s => {
        if (s?.application) {
            names.add(s.application);
        }
    });
    return names;
}

// generatedAppNamesAcrossAppSets returns the union of every Application name
// claimed by any of the given ApplicationSets.
function generatedAppNamesAcrossAppSets(appSets: models.ApplicationSet[]): Set<string> {
    const all = new Set<string>();
    appSets.forEach(appSet => {
        getAppSetGeneratedAppNames(appSet).forEach(name => all.add(name));
    });
    return all;
}

// appsInProject returns the Applications whose spec.project matches projectName.
export function appsInProject(apps: models.Application[], projectName: string): models.Application[] {
    return apps.filter(app => app.spec.project === projectName);
}

// standaloneApps returns the Applications that are NOT generated by any of the
// loaded ApplicationSets.
export function standaloneApps(apps: models.Application[], appSets: models.ApplicationSet[]): models.Application[] {
    const generated = generatedAppNamesAcrossAppSets(appSets);
    return apps.filter(app => !generated.has(app.metadata.name));
}

// appSetsInProject returns the ApplicationSets that generate at least one
// Application in the given project. ApplicationSets have no project of their
// own, so membership is derived from the Applications they generate.
export function appSetsInProject(apps: models.Application[], appSets: models.ApplicationSet[], projectName: string): models.ApplicationSet[] {
    const appByName = new Map(apps.map(app => [app.metadata.name, app]));
    return appSets.filter(appSet => {
        const names: string[] = [];
        getAppSetGeneratedAppNames(appSet).forEach(n => names.push(n));
        return names.some(name => {
            const app = appByName.get(name);
            return !!app && app.spec.project === projectName;
        });
    });
}

// appsOwnedByAppSet returns the Applications generated by the named ApplicationSet.
export function appsOwnedByAppSet(apps: models.Application[], appSets: models.ApplicationSet[], appSetName: string): models.Application[] {
    const appSet = appSets.find(as => as.metadata.name === appSetName);
    if (!appSet) {
        return [];
    }
    const names = getAppSetGeneratedAppNames(appSet);
    return apps.filter(app => names.has(app.metadata.name));
}
